[package]
name = "ff_rithmic_api"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
toml = "*"
dashmap ="*"
ahash ="*"
prost ="*"
prost-build = "0.13.2"
tokio-tungstenite = { version = "0.23.1", features = ["stream", "native-tls"] }
tungstenite = "0.24.0"
futures-util = "0.3.30"
url = "2.5.2"
tokio =  { version = "*", features = ["full"] }
chrono = "*"