user = "{ASK_RITHMIC_FOR_CREDENTIALS}"
server_name = "Test"
system_name = "Test"
app_name = "Example"
app_version = "1.0"
password = "password"
fcm_id = "XXXFIRM"
ib_id = "XXXFIRM"
user_type = 3
subscribe_data = true
aggregated_quotes = true