user = ""
system_name = ""
password = ""
app_name = ""
app_version = "1.0"
aggregated_quotes = false
template_version = "5.27"
pem = "/rithmic_ssl_cert_auth_params.pem"
base_url = "wss://rituz00100.rithmic.com:443"
